### ISSUE TITLE
Optimize Initial Page Load

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#79]
Some Testing via incognito tab:

Intermittently slow js loading (js file was not updated or modified):
![image](https://cloud.githubusercontent.com/assets/75921/14412767/77305ac0-ff9c-11e5-8c75-b9afc9759a8a.png)

Seems like github is not really that optimized for fast loading of static assets?
![image](https://cloud.githubusercontent.com/assets/75921/14412782/d320b2a8-ff9c-11e5-990d-3686d1f70637.png)

**Comment by thirdy** [comment]
Might use:
https://www.cloudflare.com
once we have our official domain name
@trackpete, any advice?

**Comment by pete-wn** [comment]
Is that .js file doing any processing? If so, it may be slow queries/etc. that are running. Otherwise, that's really weird since it's only 1.7kb, it shouldn't ever really be slow. Must be a github.io issue. Even that png file is crazy slow. 

Best bet might be to host the site somewhere else if it's routinely a problem.

**Comment by Eruyome** [comment]
GIthub Pages uses a CDN, it's pretty good and fast but you can't leverage browser caching. 

I don't know what's going on with these tests, I don't trust them. Here's a test I did.
![test](https://cloud.githubusercontent.com/assets/16058242/14453201/9f5a89e2-0093-11e6-82d2-81d51eee1ab4.jpg)

Not sure how long these tests here are saved/cached, just start a new one if you like. 
http://www.webpagetest.org/result/160412_8N_3e67afc4dd03cd9fb450c96423685500/1/details/

**Comment by thirdy** [comment]
optimizations are looking great. closing
