### ISSUE TITLE
quality Recipe search.

### ISSUE THREAD

**Issue by Manabarb** [exiletrade/exiletrade#80]
So we can look into our own items and find a match for exact blacksmith or glassblowers.
Acquisition, last time i checked, was trash for doing that, it was better if you did the math yourself.

I think all we need is put the items on public stash tabs and check for quality on item groups for an user.

**Comment by thirdy** [comment]
as a start, you can search for your own items via:

seller[account or ign name].

For example:

[sellerManicCompression](http://exiletrade.github.io/?q=sellerManicCompression)

_shameless plug_

do people actually use the blacksmith whetstone recipe? that like 40% quality on weapons right?

---

not directly related, but here's an interesting stuff that is probable to achieve: Finding items that would complete a regal recipe under only x amount of currency:

This I believe would achieve that:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline.html

I suggest making a separate html page as a prototype so this can easily be explored. We can then host it under ExileTrade but just a separate html page (at least for now)

**Comment by Manabarb** [comment]
It's great for chisels :3

**Comment by Eruyome** [comment]
Why would anyone use exiletrade to find items for scraps/whetstone/boubles/chisels recipe? Probably nobody uses scrap/whetstone recipes, for boubles you just have a tab and dump all quality flasks you find, or dump all flasks and use the search field ingame "quality" to quickly see all quality flasks. You could do that and quickly go through all your tabs with arrow keys. To find hammers for chisels you can do the same, if you do it right you would have tabs for hammers anyway and just spam whetstones to quality everything to 20%. I don't see any reason to use any kind of tool for quality recipes, not even for gems. Tools wouldn't even make you faster.

Regarding the regal recipe: You mean searching all items you're selling and find a set of items with total cost of less than X for the recipe? You probably wouldn't sell your items cheap enough to even find a complete set where the total cost is less than the value of a regal orb. Personally I just dump all recipe items in a few chaos/regal tabs and collect them there for a bit while setting 1 chaos/regal buyouts for these tabs. Either those items sell or I vendor them for the recipe. 

I'll close this ticket because I think that's an unnecessary feature, open it again if you think otherwise. The regal recipe feature should get it's own issue if we want to implement it.
