### ISSUE TITLE
Add search term for flask mods

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#83]
https://www.reddit.com/r/pathofexile/comments/4f1hfu/exiletrade_new_domain_name_input/d25bli6

search terms like `Seething` or `Surgeon'?s?` would be really useful

**Comment by kyri0** [comment]
Added all Flask mods except: 

Saturated
Cautious
Sapping
Caustic

They're double mods and exiletools don't work on that way, it separates all mods, even though some just appear together. Also can't play so my only source is the official page, which doesn't have the same names as the mapping from the exiletools, so I didn't try those out because they're mostly useless/not sought.

But a problem remain, they do not work. Some are recognized as valid search terms but do not display results, others aren't even considered valid (I already restarted the server after adding them). Asked @zocke1r for help.

**Comment by kyri0** [comment]
@zocke1r fixed them
